from django.urls import path

from . import (
    staff_access,
    staff_access_v2,
    staff_appeals,
    staff_documents,
    staff_finance,
    staff_governance,
    staff_line_workspace,
    staff_more,
    staff_workbench,
    staff_tasks,
    staff_workspace,
)


app_name = "staff_workspace"

urlpatterns = [
    path("panel/", staff_workbench.workspace_workbench, name="workbench"),
    path("", staff_workspace.workspace_dashboard, name="home"),
    path("tasks/", staff_tasks.workspace_tasks, name="tasks"),
    path("search/", staff_workspace.workspace_search, name="search"),
    path("accounts/", staff_workspace.workspace_accounts, name="accounts"),
    path("accounts/<int:account_id>/edit/", staff_registry_edit.workspace_account_edit, name="account_edit"),
    path("plots/<int:plot_id>/edit/", staff_registry_edit.workspace_land_plot_edit, name="plot_edit"),
    path("water/line/", staff_line_workspace.workspace_line, name="water_line"),
    path("water/", staff_line_workspace.workspace_water_entry, name="water"),
    path("appeals/", staff_appeals.workspace_appeals, name="appeals"),
    path("appeals/<int:appeal_id>/", staff_appeals.workspace_appeal, name="appeal"),
    path(
        "appeals/attachment/<int:attachment_id>/",
        staff_appeals.workspace_appeal_attachment,
        name="appeal_attachment",
    ),
    path("finance/", staff_finance.workspace_finance, name="finance"),
    path("finance/periods/<int:period_id>/", staff_finance.workspace_finance_period, name="finance_period"),
    path("finance/payments/", staff_finance.workspace_finance_payments, name="finance_payments"),
    path("finance/payments/new/", staff_finance.workspace_finance_payment_create, name="finance_payment_create"),
    path("finance/payments/<int:payment_id>/", staff_finance.workspace_finance_payment, name="finance_payment"),
    path("finance/accounts/<int:account_id>/", staff_finance.workspace_finance_account, name="finance_account"),
    path("access/", staff_access.workspace_access, name="access"),
    path("access/people/", staff_access_v2.workspace_access_people, name="access_people"),
    path("access/people/<int:person_id>/", staff_access_v2.workspace_access_person, name="access_person"),
    path("access/people/<int:person_id>/edit/", staff_registry_edit.workspace_person_edit, name="person_edit"),
    path("access/people/new/", staff_access.workspace_access_person_create, name="access_person_create"),
    path("access/invite/", staff_access.workspace_access_invite, name="access_invite"),
    path("access/requests/<int:request_id>/", staff_access.workspace_access_request, name="access_request"),
    path("access/accesses/<int:access_id>/", staff_access.workspace_access_detail, name="access_detail"),
    path("access/grants/<int:grant_id>/", staff_access.workspace_grant_detail, name="grant_detail"),
    path(
        "access/invites/<int:invite_id>/revoke/",
        staff_access.workspace_access_revoke_invite,
        name="access_revoke_invite",
    ),
    path(
        "access/resets/<int:reset_id>/revoke/",
        staff_access.workspace_access_revoke_reset,
        name="access_revoke_reset",
    ),
    path("documents/", staff_documents.workspace_documents, name="documents"),
    path("documents/accounts/new/", staff_documents.workspace_account_document_create, name="account_document_create"),
    path("documents/accounts/<int:document_id>/", staff_documents.workspace_account_document, name="account_document"),
    path(
        "documents/accounts/<int:document_id>/download/",
        staff_documents.workspace_account_document_download,
        name="account_document_download",
    ),
    path("documents/public/new/", staff_documents.workspace_public_document_create, name="public_document_create"),
    path("documents/public/<int:document_id>/", staff_documents.workspace_public_document, name="public_document"),
    path(
        "documents/public/<int:document_id>/download/",
        staff_documents.workspace_public_document_download,
        name="public_document_download",
    ),
    path("documents/news/new/", staff_documents.workspace_news_create, name="news_create"),
    path("documents/news/<int:news_id>/", staff_documents.workspace_news, name="news"),
    path("governance/", staff_governance.workspace_governance, name="governance"),
    path("governance/new/", staff_governance.workspace_governance_create, name="governance_create"),
    path("governance/<int:poll_id>/", staff_governance.workspace_governance_detail, name="governance_detail"),
    path("more/roles-guide/", staff_more.workspace_roles_guide, name="roles_guide"),
    path("more/", staff_more.workspace_more, name="more"),
    path("accounts/<int:account_id>/", staff_workspace.workspace_account, name="account"),
]

