# Generated by Django 5.2.17 on 2026-09-15 10:36

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=0)),
                ('seed_slot', models.PositiveIntegerField(editable=False, null=True, unique=True)),
                ('number', models.CharField(blank=True, max_length=40, null=True, unique=True, verbose_name='Лицевой счёт')),
                ('plot', models.CharField(blank=True, max_length=200, verbose_name='Участок / адрес')),
                ('contact_name', models.CharField(blank=True, max_length=200, verbose_name='ФИО контактного лица')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='Телефон')),
                ('notes', models.TextField(blank=True, verbose_name='Примечание')),
                ('archived', models.BooleanField(default=False, verbose_name='Архивная карточка')),
            ],
            options={
                'verbose_name': 'Лицевой счёт',
                'verbose_name_plural': '01 · Лицевые счета',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SupplyNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Общий узел водоснабжения')),
                ('notes', models.TextField(blank=True, verbose_name='Примечание')),
            ],
            options={
                'verbose_name': 'Общий узел',
                'verbose_name_plural': '02 · Общие узлы',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalAccount',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=0)),
                ('seed_slot', models.PositiveIntegerField(db_index=True, editable=False, null=True)),
                ('number', models.CharField(blank=True, db_index=True, max_length=40, null=True, verbose_name='Лицевой счёт')),
                ('plot', models.CharField(blank=True, max_length=200, verbose_name='Участок / адрес')),
                ('contact_name', models.CharField(blank=True, max_length=200, verbose_name='ФИО контактного лица')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='Телефон')),
                ('notes', models.TextField(blank=True, verbose_name='Примечание')),
                ('archived', models.BooleanField(default=False, verbose_name='Архивная карточка')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Лицевой счёт',
                'verbose_name_plural': 'historical 01 · Лицевые счета',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalSupplyNode',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Общий узел водоснабжения')),
                ('notes', models.TextField(blank=True, verbose_name='Примечание')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Общий узел',
                'verbose_name_plural': 'historical 02 · Общие узлы',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=0)),
                ('serial', models.CharField(max_length=100, verbose_name='Номер / обозначение счётчика')),
                ('kind', models.CharField(choices=[('main', 'Общий'), ('line', 'Линии / контрольный'), ('individual', 'Индивидуальный'), ('irrigation', 'Полив')], max_length=20, verbose_name='Назначение')),
                ('retired_on', models.DateField(blank=True, null=True, verbose_name='Снят с учёта')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='water.account', verbose_name='Лицевой счёт')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='water.supplynode', verbose_name='Общий узел')),
            ],
            options={
                'verbose_name': 'Счётчик',
                'verbose_name_plural': '05 · Счётчики',
            },
        ),
        migrations.CreateModel(
            name='HistoricalReading',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=0)),
                ('date', models.DateField(verbose_name='Дата снятия')),
                ('value', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Показание счётчика, м³')),
                ('notes', models.TextField(blank=True, verbose_name='Примечание')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('meter', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='water.meter', verbose_name='Счётчик')),
            ],
            options={
                'verbose_name': 'historical Показание счётчика',
                'verbose_name_plural': 'historical 06 · Показания счётчиков',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalWaterGroup',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Линия / группа')),
                ('source', models.CharField(choices=[('unknown', 'Пока не определён'), ('reported', 'Кубы, переданные старшим'), ('individual', 'Сумма индивидуальных расходов'), ('meter', 'Счётчик линии')], default='unknown', max_length=20, verbose_name='Основной источник расхода')),
                ('notes', models.TextField(blank=True, verbose_name='Примечание')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('node', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='water.supplynode', verbose_name='Общий узел')),
            ],
            options={
                'verbose_name': 'historical Линия / группа',
                'verbose_name_plural': 'historical 03 · Линии и группы',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='WaterGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Линия / группа')),
                ('source', models.CharField(choices=[('unknown', 'Пока не определён'), ('reported', 'Кубы, переданные старшим'), ('individual', 'Сумма индивидуальных расходов'), ('meter', 'Счётчик линии')], default='unknown', max_length=20, verbose_name='Основной источник расхода')),
                ('notes', models.TextField(blank=True, verbose_name='Примечание')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='water.supplynode', verbose_name='Общий узел')),
            ],
            options={
                'verbose_name': 'Линия / группа',
                'verbose_name_plural': '03 · Линии и группы',
            },
        ),
        migrations.AddField(
            model_name='meter',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='water.watergroup', verbose_name='Линия / группа'),
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=0)),
                ('starts', models.DateField(verbose_name='В группе с')),
                ('ends', models.DateField(blank=True, null=True, verbose_name='В группе до (не включая)')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='water.account', verbose_name='Лицевой счёт')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='water.watergroup', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Участник группы',
                'verbose_name_plural': '04 · Состав групп',
            },
        ),
        migrations.CreateModel(
            name='HistoricalMeter',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=0)),
                ('serial', models.CharField(max_length=100, verbose_name='Номер / обозначение счётчика')),
                ('kind', models.CharField(choices=[('main', 'Общий'), ('line', 'Линии / контрольный'), ('individual', 'Индивидуальный'), ('irrigation', 'Полив')], max_length=20, verbose_name='Назначение')),
                ('retired_on', models.DateField(blank=True, null=True, verbose_name='Снят с учёта')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('account', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='water.account', verbose_name='Лицевой счёт')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('node', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='water.supplynode', verbose_name='Общий узел')),
                ('group', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='water.watergroup', verbose_name='Линия / группа')),
            ],
            options={
                'verbose_name': 'historical Счётчик',
                'verbose_name_plural': 'historical 05 · Счётчики',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalMembership',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=0)),
                ('starts', models.DateField(verbose_name='В группе с')),
                ('ends', models.DateField(blank=True, null=True, verbose_name='В группе до (не включая)')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('account', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='water.account', verbose_name='Лицевой счёт')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='water.watergroup', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'historical Участник группы',
                'verbose_name_plural': 'historical 04 · Состав групп',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalGroupConsumption',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=0)),
                ('starts', models.DateField(verbose_name='Начало периода')),
                ('ends', models.DateField(verbose_name='Конец периода (не включая)')),
                ('volume', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Расход группы за период, м³')),
                ('reported_by', models.CharField(max_length=200, verbose_name='Кто передал / старший')),
                ('notes', models.TextField(blank=True, verbose_name='Примечание')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='water.watergroup', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'historical Расход группы',
                'verbose_name_plural': 'historical 07 · Кубы от старших',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='GroupConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=0)),
                ('starts', models.DateField(verbose_name='Начало периода')),
                ('ends', models.DateField(verbose_name='Конец периода (не включая)')),
                ('volume', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Расход группы за период, м³')),
                ('reported_by', models.CharField(max_length=200, verbose_name='Кто передал / старший')),
                ('notes', models.TextField(blank=True, verbose_name='Примечание')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='water.watergroup', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Расход группы',
                'verbose_name_plural': '07 · Кубы от старших',
                'ordering': ['-starts', 'group'],
            },
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=0)),
                ('date', models.DateField(verbose_name='Дата снятия')),
                ('value', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Показание счётчика, м³')),
                ('notes', models.TextField(blank=True, verbose_name='Примечание')),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='water.meter', verbose_name='Счётчик')),
            ],
            options={
                'verbose_name': 'Показание счётчика',
                'verbose_name_plural': '06 · Показания счётчиков',
                'ordering': ['-date', '-id'],
                'constraints': [models.UniqueConstraint(fields=('meter', 'date'), name='reading_meter_date'), models.CheckConstraint(condition=models.Q(('value__gte', 0)), name='reading_nonnegative')],
            },
        ),
        migrations.AddConstraint(
            model_name='meter',
            constraint=models.UniqueConstraint(fields=('node', 'serial'), name='meter_node_serial'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.CheckConstraint(condition=models.Q(('ends__isnull', True), ('ends__gt', models.F('starts')), _connector='OR'), name='membership_dates'),
        ),
        migrations.AddConstraint(
            model_name='groupconsumption',
            constraint=models.CheckConstraint(condition=models.Q(('ends__gt', models.F('starts'))), name='group_period_dates'),
        ),
        migrations.AddConstraint(
            model_name='groupconsumption',
            constraint=models.CheckConstraint(condition=models.Q(('volume__gte', 0)), name='group_volume_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='groupconsumption',
            constraint=models.UniqueConstraint(fields=('group', 'starts', 'ends'), name='group_period_unique'),
        ),
    ]
