# Generated by Django 5.2.17 on 2026-09-17 12:40

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0002_account_export_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=0)),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Электронная почта')),
                ('notes', models.TextField(blank=True, verbose_name='Примечание')),
                ('archived', models.BooleanField(default=False, verbose_name='Архивная карточка человека')),
            ],
            options={
                'verbose_name': 'Человек',
                'verbose_name_plural': '02 · Люди',
                'ordering': ['full_name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalLandPlot',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=0)),
                ('label', models.CharField(max_length=100, verbose_name='Обозначение участка')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='Адрес / ориентир')),
                ('cadastral_number', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Кадастровый номер')),
                ('notes', models.TextField(blank=True, verbose_name='Примечание')),
                ('archived', models.BooleanField(default=False, verbose_name='Архивный участок')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('account', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='water.account', verbose_name='Лицевой счёт')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Участок',
                'verbose_name_plural': 'historical 03 · Участки',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPerson',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=0)),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Электронная почта')),
                ('notes', models.TextField(blank=True, verbose_name='Примечание')),
                ('archived', models.BooleanField(default=False, verbose_name='Архивная карточка человека')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Человек',
                'verbose_name_plural': 'historical 02 · Люди',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='LandPlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=0)),
                ('label', models.CharField(max_length=100, verbose_name='Обозначение участка')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='Адрес / ориентир')),
                ('cadastral_number', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Кадастровый номер')),
                ('notes', models.TextField(blank=True, verbose_name='Примечание')),
                ('archived', models.BooleanField(default=False, verbose_name='Архивный участок')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='land_plots', to='water.account', verbose_name='Лицевой счёт')),
            ],
            options={
                'verbose_name': 'Участок',
                'verbose_name_plural': '03 · Участки',
                'ordering': ['label', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalPlotRelation',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=0)),
                ('role', models.CharField(choices=[('owner', 'Собственник'), ('representative', 'Представитель')], max_length=20, verbose_name='Статус')),
                ('starts', models.DateField(verbose_name='Действует с')),
                ('ends', models.DateField(blank=True, null=True, verbose_name='Действует до (не включая)')),
                ('document', models.CharField(blank=True, max_length=300, verbose_name='Основание / документ')),
                ('notes', models.TextField(blank=True, verbose_name='Примечание')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('plot', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='water.landplot', verbose_name='Участок')),
                ('person', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='water.person', verbose_name='Человек')),
            ],
            options={
                'verbose_name': 'historical Связь человека с участком',
                'verbose_name_plural': 'historical 04 · Владение и представительство',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PlotRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=0)),
                ('role', models.CharField(choices=[('owner', 'Собственник'), ('representative', 'Представитель')], max_length=20, verbose_name='Статус')),
                ('starts', models.DateField(verbose_name='Действует с')),
                ('ends', models.DateField(blank=True, null=True, verbose_name='Действует до (не включая)')),
                ('document', models.CharField(blank=True, max_length=300, verbose_name='Основание / документ')),
                ('notes', models.TextField(blank=True, verbose_name='Примечание')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plot_relations', to='water.person', verbose_name='Человек')),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relations', to='water.landplot', verbose_name='Участок')),
            ],
            options={
                'verbose_name': 'Связь человека с участком',
                'verbose_name_plural': '04 · Владение и представительство',
                'ordering': ['plot', '-starts', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('ends__isnull', True), ('ends__gt', models.F('starts')), _connector='OR'), name='plot_relation_dates')],
            },
        ),
    ]
