# Generated by Django 5.2.17 on 2026-09-17 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0003_person_historicallandplot_historicalperson_landplot_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reading',
            options={'ordering': ['-date', '-id'], 'permissions': [('export_reading', 'Может выгружать показания в CSV')], 'verbose_name': 'Показание счётчика', 'verbose_name_plural': '06 · Показания счётчиков'},
        ),
        migrations.AddField(
            model_name='historicalmeter',
            name='commissioned_on',
            field=models.DateField(blank=True, null=True, verbose_name='Установлен / принят на учёт'),
        ),
        migrations.AddField(
            model_name='historicalmeter',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Примечание'),
        ),
        migrations.AddField(
            model_name='historicalmeter',
            name='seal_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Номер пломбы'),
        ),
        migrations.AddField(
            model_name='meter',
            name='commissioned_on',
            field=models.DateField(blank=True, null=True, verbose_name='Установлен / принят на учёт'),
        ),
        migrations.AddField(
            model_name='meter',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Примечание'),
        ),
        migrations.AddField(
            model_name='meter',
            name='seal_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Номер пломбы'),
        ),
    ]
