# Generated by Django 5.2.17 on 2026-09-17 18:59

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0005_billingpolicy_billingperiod_charge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallandplot',
            name='area_m2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Площадь, м²'),
        ),
        migrations.AddField(
            model_name='landplot',
            name='area_m2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Площадь, м²'),
        ),
    ]
