# Generated by Django 5.2.17 on 2026-09-17 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0006_historicallandplot_area_m2_landplot_area_m2'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingpolicy',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='Правила по умолчанию'),
        ),
        migrations.AddField(
            model_name='charge',
            name='origin',
            field=models.CharField(choices=[('manual', 'Ручной ввод'), ('calculation', 'Автоматический расчёт'), ('import', 'Импорт')], default='manual', max_length=20, verbose_name='Источник'),
        ),
        migrations.AddField(
            model_name='charge',
            name='source_key',
            field=models.CharField(blank=True, editable=False, max_length=200, null=True, unique=True, verbose_name='Ключ автоматического расчёта'),
        ),
        migrations.AddField(
            model_name='historicalbillingpolicy',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='Правила по умолчанию'),
        ),
        migrations.AddField(
            model_name='historicalcharge',
            name='origin',
            field=models.CharField(choices=[('manual', 'Ручной ввод'), ('calculation', 'Автоматический расчёт'), ('import', 'Импорт')], default='manual', max_length=20, verbose_name='Источник'),
        ),
        migrations.AddField(
            model_name='historicalcharge',
            name='source_key',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=200, null=True, verbose_name='Ключ автоматического расчёта'),
        ),
        migrations.AddConstraint(
            model_name='billingpolicy',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('is_default',), name='single_default_billing_policy'),
        ),
    ]
