# Generated by Django 5.2.17 on 2026-09-17 19:09

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0007_billingpolicy_is_default_charge_origin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Тариф'),
        ),
        migrations.AlterField(
            model_name='charge',
            name='volume',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Объём, м³'),
        ),
        migrations.AlterField(
            model_name='historicalcharge',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Тариф'),
        ),
        migrations.AlterField(
            model_name='historicalcharge',
            name='volume',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Объём, м³'),
        ),
    ]
