# Generated by Django 5.2.17 on 2026-09-18 05:18

import django.core.validators
import django.db.models.deletion
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0008_alter_charge_rate_alter_charge_volume_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=0)),
                ('filename', models.CharField(max_length=255, verbose_name='Имя исходного файла')),
                ('sha256', models.CharField(editable=False, max_length=64, unique=True, verbose_name='Контрольная сумма SHA-256')),
                ('sheet', models.CharField(blank=True, max_length=200, verbose_name='Лист / источник')),
                ('effective_date', models.DateField(verbose_name='Дата, с которой действуют данные')),
                ('status', models.CharField(choices=[('staged', 'Предварительно загружен'), ('partial', 'Применён частично'), ('applied', 'Применён полностью'), ('rejected', 'Отклонён')], default='staged', max_length=20, verbose_name='Состояние')),
                ('row_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='Строк распознано')),
                ('notes', models.TextField(blank=True, verbose_name='Примечание')),
            ],
            options={
                'verbose_name': 'Пакет импорта',
                'verbose_name_plural': '15 · Безопасный импорт',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalImportBatch',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=0)),
                ('filename', models.CharField(max_length=255, verbose_name='Имя исходного файла')),
                ('sha256', models.CharField(db_index=True, editable=False, max_length=64, verbose_name='Контрольная сумма SHA-256')),
                ('sheet', models.CharField(blank=True, max_length=200, verbose_name='Лист / источник')),
                ('effective_date', models.DateField(verbose_name='Дата, с которой действуют данные')),
                ('status', models.CharField(choices=[('staged', 'Предварительно загружен'), ('partial', 'Применён частично'), ('applied', 'Применён полностью'), ('rejected', 'Отклонён')], default='staged', max_length=20, verbose_name='Состояние')),
                ('row_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='Строк распознано')),
                ('notes', models.TextField(blank=True, verbose_name='Примечание')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Пакет импорта',
                'verbose_name_plural': 'historical 15 · Безопасный импорт',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalImportRow',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=0)),
                ('row_number', models.PositiveIntegerField(verbose_name='Строка файла')),
                ('account_number', models.CharField(blank=True, max_length=40, verbose_name='Лицевой счёт')),
                ('plot_label', models.CharField(blank=True, max_length=100, verbose_name='Участок')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='Адрес / ориентир')),
                ('cadastral_number', models.CharField(blank=True, max_length=50, verbose_name='Кадастровый номер')),
                ('area_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Площадь, м²')),
                ('person_name', models.CharField(blank=True, max_length=200, verbose_name='ФИО')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Электронная почта')),
                ('status', models.CharField(choices=[('ready', 'Готово к применению'), ('review', 'Требует проверки'), ('applied', 'Применено'), ('skipped', 'Пропущено')], default='review', max_length=20, verbose_name='Результат проверки')),
                ('issues', models.TextField(blank=True, verbose_name='Замечания')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('applied_account', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='water.account', verbose_name='Созданный/найденный счёт')),
                ('applied_person', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='water.person', verbose_name='Созданный/найденный человек')),
                ('applied_plot', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='water.landplot', verbose_name='Созданный/найденный участок')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='water.importbatch', verbose_name='Пакет')),
            ],
            options={
                'verbose_name': 'historical Строка импорта',
                'verbose_name_plural': 'historical 16 · Строки импорта',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ImportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=0)),
                ('row_number', models.PositiveIntegerField(verbose_name='Строка файла')),
                ('account_number', models.CharField(blank=True, max_length=40, verbose_name='Лицевой счёт')),
                ('plot_label', models.CharField(blank=True, max_length=100, verbose_name='Участок')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='Адрес / ориентир')),
                ('cadastral_number', models.CharField(blank=True, max_length=50, verbose_name='Кадастровый номер')),
                ('area_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Площадь, м²')),
                ('person_name', models.CharField(blank=True, max_length=200, verbose_name='ФИО')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Электронная почта')),
                ('status', models.CharField(choices=[('ready', 'Готово к применению'), ('review', 'Требует проверки'), ('applied', 'Применено'), ('skipped', 'Пропущено')], default='review', max_length=20, verbose_name='Результат проверки')),
                ('issues', models.TextField(blank=True, verbose_name='Замечания')),
                ('applied_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='water.account', verbose_name='Созданный/найденный счёт')),
                ('applied_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='water.person', verbose_name='Созданный/найденный человек')),
                ('applied_plot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='water.landplot', verbose_name='Созданный/найденный участок')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rows', to='water.importbatch', verbose_name='Пакет')),
            ],
            options={
                'verbose_name': 'Строка импорта',
                'verbose_name_plural': '16 · Строки импорта',
                'ordering': ['batch', 'row_number'],
                'constraints': [models.UniqueConstraint(fields=('batch', 'row_number'), name='import_batch_row_unique')],
            },
        ),
    ]
