# Generated by Django 5.2.17 on 2026-09-18 06:07

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0009_importbatch_historicalimportbatch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalResidentAccess',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=0)),
                ('role', models.CharField(choices=[('owner', 'Собственник'), ('representative', 'Представитель'), ('payer', 'Плательщик')], max_length=20, verbose_name='Основание доступа')),
                ('starts', models.DateField(verbose_name='Доступ с')),
                ('ends', models.DateField(blank=True, null=True, verbose_name='Доступ до (не включая)')),
                ('verified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Подтверждён')),
                ('notes', models.TextField(blank=True, verbose_name='Примечание')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('account', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='water.account', verbose_name='Лицевой счёт')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Житель')),
            ],
            options={
                'verbose_name': 'historical Доступ жителя',
                'verbose_name_plural': 'historical 17 · Доступ жителей',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalResidentInvite',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=0)),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('role', models.CharField(choices=[('owner', 'Собственник'), ('representative', 'Представитель'), ('payer', 'Плательщик')], max_length=20, verbose_name='Основание доступа')),
                ('token_hash', models.CharField(db_index=True, editable=False, max_length=64, verbose_name='Хэш приглашения')),
                ('expires_at', models.DateTimeField(verbose_name='Действует до')),
                ('used_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Использовано')),
                ('revoked', models.BooleanField(default=False, verbose_name='Отозвано')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('account', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='water.account', verbose_name='Лицевой счёт')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Приглашение жителя',
                'verbose_name_plural': 'historical 18 · Приглашения жителей',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ResidentInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=0)),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('role', models.CharField(choices=[('owner', 'Собственник'), ('representative', 'Представитель'), ('payer', 'Плательщик')], max_length=20, verbose_name='Основание доступа')),
                ('token_hash', models.CharField(editable=False, max_length=64, unique=True, verbose_name='Хэш приглашения')),
                ('expires_at', models.DateTimeField(verbose_name='Действует до')),
                ('used_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Использовано')),
                ('revoked', models.BooleanField(default=False, verbose_name='Отозвано')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resident_invites', to='water.account', verbose_name='Лицевой счёт')),
            ],
            options={
                'verbose_name': 'Приглашение жителя',
                'verbose_name_plural': '18 · Приглашения жителей',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ResidentAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=0)),
                ('role', models.CharField(choices=[('owner', 'Собственник'), ('representative', 'Представитель'), ('payer', 'Плательщик')], max_length=20, verbose_name='Основание доступа')),
                ('starts', models.DateField(verbose_name='Доступ с')),
                ('ends', models.DateField(blank=True, null=True, verbose_name='Доступ до (не включая)')),
                ('verified_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Подтверждён')),
                ('notes', models.TextField(blank=True, verbose_name='Примечание')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resident_accesses', to='water.account', verbose_name='Лицевой счёт')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resident_accesses', to=settings.AUTH_USER_MODEL, verbose_name='Житель')),
            ],
            options={
                'verbose_name': 'Доступ жителя',
                'verbose_name_plural': '17 · Доступ жителей',
                'constraints': [models.CheckConstraint(condition=models.Q(('ends__isnull', True), ('ends__gt', models.F('starts')), _connector='OR'), name='resident_access_dates')],
            },
        ),
    ]
