# Generated by Django 5.2.17 on 2026-09-18 07:05

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
import water.models
from django.conf import settings
from django.db import migrations, models


def create_default_categories(apps, schema_editor):
    AppealCategory = apps.get_model('water', 'AppealCategory')
    DocumentCategory = apps.get_model('water', 'DocumentCategory')
    for order, name in enumerate((
        'Начисления и оплаты', 'Счётчик и показания', 'Документы и справки',
        'Качество водоснабжения', 'Доступ в личный кабинет', 'Другое',
    ), 10):
        AppealCategory.objects.get_or_create(name=name, defaults={'sort_order': order * 10})
    for order, name in enumerate((
        'Квитанция', 'Акт сверки', 'Справка', 'Уведомление', 'Решение правления', 'Другой документ',
    ), 10):
        DocumentCategory.objects.get_or_create(name=name, defaults={'sort_order': order * 10})


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0010_historicalresidentaccess_historicalresidentinvite_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppealCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Тема обращения')),
                ('active', models.BooleanField(default=True, verbose_name='Доступна жителям')),
                ('sort_order', models.PositiveIntegerField(default=100, verbose_name='Порядок')),
                ('instructions', models.TextField(blank=True, verbose_name='Подсказка жителю')),
            ],
            options={
                'verbose_name': 'Тема обращения',
                'verbose_name_plural': '19 · Темы обращений',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Вид документа')),
                ('active', models.BooleanField(default=True, verbose_name='Можно выбирать')),
                ('sort_order', models.PositiveIntegerField(default=100, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Вид документа',
                'verbose_name_plural': '21 · Виды документов',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AccountDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('document', models.FileField(max_length=300, upload_to=water.models.private_document_path, verbose_name='Файл')),
                ('original_name', models.CharField(editable=False, max_length=255, verbose_name='Исходное имя файла')),
                ('file_size', models.PositiveBigIntegerField(editable=False, verbose_name='Размер, байт')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Опубликован')),
                ('visible_to_residents', models.BooleanField(default=True, verbose_name='Показывать жителям')),
                ('notes', models.TextField(blank=True, verbose_name='Служебное примечание')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='water.account', verbose_name='Лицевой счёт')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='water.documentcategory', verbose_name='Вид документа')),
            ],
            options={
                'verbose_name': 'Документ лицевого счёта',
                'verbose_name_plural': '22 · Документы жителей',
                'ordering': ['-published_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalAccountDocument',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('document', models.TextField(max_length=300, verbose_name='Файл')),
                ('original_name', models.CharField(editable=False, max_length=255, verbose_name='Исходное имя файла')),
                ('file_size', models.PositiveBigIntegerField(editable=False, verbose_name='Размер, байт')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Опубликован')),
                ('visible_to_residents', models.BooleanField(default=True, verbose_name='Показывать жителям')),
                ('notes', models.TextField(blank=True, verbose_name='Служебное примечание')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('account', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='water.account', verbose_name='Лицевой счёт')),
                ('category', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='water.documentcategory', verbose_name='Вид документа')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Документ лицевого счёта',
                'verbose_name_plural': 'historical 22 · Документы жителей',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalAppealCategory',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(db_index=True, max_length=120, verbose_name='Тема обращения')),
                ('active', models.BooleanField(default=True, verbose_name='Доступна жителям')),
                ('sort_order', models.PositiveIntegerField(default=100, verbose_name='Порядок')),
                ('instructions', models.TextField(blank=True, verbose_name='Подсказка жителю')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Тема обращения',
                'verbose_name_plural': 'historical 19 · Темы обращений',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalDocumentCategory',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(db_index=True, max_length=120, verbose_name='Вид документа')),
                ('active', models.BooleanField(default=True, verbose_name='Можно выбирать')),
                ('sort_order', models.PositiveIntegerField(default=100, verbose_name='Порядок')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Вид документа',
                'verbose_name_plural': 'historical 21 · Виды документов',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalResidentAppeal',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=0)),
                ('subject', models.CharField(max_length=180, verbose_name='Кратко о вопросе')),
                ('message', models.TextField(max_length=5000, verbose_name='Сообщение')),
                ('status', models.CharField(choices=[('new', 'Новое'), ('in_progress', 'В работе'), ('awaiting_resident', 'Нужен ответ жителя'), ('resolved', 'Решено'), ('closed', 'Закрыто')], default='new', max_length=30, verbose_name='Состояние')),
                ('response', models.TextField(blank=True, max_length=5000, verbose_name='Ответ правления')),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Создано')),
                ('responded_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Ответ дан')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('account', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='water.account', verbose_name='Лицевой счёт')),
                ('author', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Житель')),
                ('category', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='water.appealcategory', verbose_name='Тема')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('responded_by', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Ответил')),
            ],
            options={
                'verbose_name': 'historical Обращение жителя',
                'verbose_name_plural': 'historical 20 · Обращения жителей',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ResidentAppeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=0)),
                ('subject', models.CharField(max_length=180, verbose_name='Кратко о вопросе')),
                ('message', models.TextField(max_length=5000, verbose_name='Сообщение')),
                ('status', models.CharField(choices=[('new', 'Новое'), ('in_progress', 'В работе'), ('awaiting_resident', 'Нужен ответ жителя'), ('resolved', 'Решено'), ('closed', 'Закрыто')], default='new', max_length=30, verbose_name='Состояние')),
                ('response', models.TextField(blank=True, max_length=5000, verbose_name='Ответ правления')),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Создано')),
                ('responded_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Ответ дан')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appeals', to='water.account', verbose_name='Лицевой счёт')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resident_appeals', to=settings.AUTH_USER_MODEL, verbose_name='Житель')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='water.appealcategory', verbose_name='Тема')),
                ('responded_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='answered_resident_appeals', to=settings.AUTH_USER_MODEL, verbose_name='Ответил')),
            ],
            options={
                'verbose_name': 'Обращение жителя',
                'verbose_name_plural': '20 · Обращения жителей',
                'ordering': ['-opened_at', '-id'],
            },
        ),
        migrations.RunPython(create_default_categories, migrations.RunPython.noop),
    ]
