# Generated by Django 5.2.17 on 2026-09-18 07:10

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0011_appealcategory_documentcategory_accountdocument_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalResidentAppealMessage',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=0)),
                ('body', models.TextField(max_length=5000, verbose_name='Уточнение жителя')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Отправлено')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('appeal', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='water.residentappeal', verbose_name='Обращение')),
                ('author', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Житель')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Уточнение по обращению',
                'verbose_name_plural': 'historical Уточнения жителей',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ResidentAppealMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=0)),
                ('body', models.TextField(max_length=5000, verbose_name='Уточнение жителя')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Отправлено')),
                ('appeal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resident_messages', to='water.residentappeal', verbose_name='Обращение')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Житель')),
            ],
            options={
                'verbose_name': 'Уточнение по обращению',
                'verbose_name_plural': 'Уточнения жителей',
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
