# Generated by Django 5.2.17 on 2026-09-18 07:20

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0012_historicalresidentappealmessage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountdocument',
            options={'ordering': ['-published_at', '-id'], 'verbose_name': 'Документ лицевого счёта', 'verbose_name_plural': '23 · Документы жителей'},
        ),
        migrations.AlterModelOptions(
            name='appealcategory',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': 'Тема обращения', 'verbose_name_plural': '20 · Темы обращений'},
        ),
        migrations.AlterModelOptions(
            name='documentcategory',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': 'Вид документа', 'verbose_name_plural': '22 · Виды документов'},
        ),
        migrations.AlterModelOptions(
            name='historicalaccountdocument',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Документ лицевого счёта', 'verbose_name_plural': 'historical 23 · Документы жителей'},
        ),
        migrations.AlterModelOptions(
            name='historicalappealcategory',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Тема обращения', 'verbose_name_plural': 'historical 20 · Темы обращений'},
        ),
        migrations.AlterModelOptions(
            name='historicaldocumentcategory',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Вид документа', 'verbose_name_plural': 'historical 22 · Виды документов'},
        ),
        migrations.AlterModelOptions(
            name='historicalresidentappeal',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Обращение жителя', 'verbose_name_plural': 'historical 21 · Обращения жителей'},
        ),
        migrations.AlterModelOptions(
            name='residentappeal',
            options={'ordering': ['-opened_at', '-id'], 'verbose_name': 'Обращение жителя', 'verbose_name_plural': '21 · Обращения жителей'},
        ),
        migrations.CreateModel(
            name='HistoricalResidentPasswordReset',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=0)),
                ('token_hash', models.CharField(db_index=True, editable=False, max_length=64, verbose_name='Хэш ссылки')),
                ('expires_at', models.DateTimeField(verbose_name='Действует до')),
                ('used_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Использовано')),
                ('revoked', models.BooleanField(default=False, verbose_name='Отозвано')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Житель')),
            ],
            options={
                'verbose_name': 'historical Восстановление доступа жителя',
                'verbose_name_plural': 'historical 19 · Восстановление доступа',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ResidentPasswordReset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=0)),
                ('token_hash', models.CharField(editable=False, max_length=64, unique=True, verbose_name='Хэш ссылки')),
                ('expires_at', models.DateTimeField(verbose_name='Действует до')),
                ('used_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Использовано')),
                ('revoked', models.BooleanField(default=False, verbose_name='Отозвано')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resident_password_resets', to=settings.AUTH_USER_MODEL, verbose_name='Житель')),
            ],
            options={
                'verbose_name': 'Восстановление доступа жителя',
                'verbose_name_plural': '19 · Восстановление доступа',
                'ordering': ['-id'],
            },
        ),
    ]
