# Generated by Django 5.2.17 on 2026-09-18 16:22

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import simple_history.models
import water.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0013_alter_accountdocument_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControllerReadingSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=0)),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата снятия')),
                ('value', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Показание, м³')),
                ('photo', models.FileField(max_length=300, upload_to=water.models.controller_reading_photo_path, verbose_name='Фото счётчика')),
                ('notes', models.TextField(blank=True, max_length=500, verbose_name='Примечание')),
                ('status', models.CharField(choices=[('pending', 'На проверке'), ('approved', 'Принято'), ('rejected', 'Отклонено')], default='pending', editable=False, max_length=20, verbose_name='Статус')),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Отправлено')),
                ('reviewed_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Проверено')),
                ('review_comment', models.CharField(blank=True, editable=False, max_length=500, verbose_name='Комментарий проверки')),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='water.meter', verbose_name='Счётчик')),
                ('reading', models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='water.reading', verbose_name='Созданное показание')),
                ('reviewed_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_controller_readings', to=settings.AUTH_USER_MODEL, verbose_name='Проверил')),
                ('submitted_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='controller_reading_submissions', to=settings.AUTH_USER_MODEL, verbose_name='Контролёр')),
            ],
            options={
                'verbose_name': 'Показание контролёра',
                'verbose_name_plural': '07 · Премодерация показаний',
                'ordering': ['status', '-submitted_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalControllerReadingSubmission',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=0)),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата снятия')),
                ('value', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Показание, м³')),
                ('photo', models.TextField(max_length=300, verbose_name='Фото счётчика')),
                ('notes', models.TextField(blank=True, max_length=500, verbose_name='Примечание')),
                ('status', models.CharField(choices=[('pending', 'На проверке'), ('approved', 'Принято'), ('rejected', 'Отклонено')], default='pending', editable=False, max_length=20, verbose_name='Статус')),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Отправлено')),
                ('reviewed_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Проверено')),
                ('review_comment', models.CharField(blank=True, editable=False, max_length=500, verbose_name='Комментарий проверки')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('meter', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='water.meter', verbose_name='Счётчик')),
                ('reading', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='water.reading', verbose_name='Созданное показание')),
                ('reviewed_by', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Проверил')),
                ('submitted_by', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Контролёр')),
            ],
            options={
                'verbose_name': 'historical Показание контролёра',
                'verbose_name_plural': 'historical 07 · Премодерация показаний',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
