# Generated by Django 5.2.17 on 2026-09-21 05:06

import water.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0014_controllerreadingsubmission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controllerreadingsubmission',
            name='photo',
            field=models.FileField(blank=True, max_length=300, upload_to=water.models.controller_reading_photo_path, verbose_name='Фото счётчика'),
        ),
        migrations.AlterField(
            model_name='historicalcontrollerreadingsubmission',
            name='photo',
            field=models.TextField(blank=True, max_length=300, verbose_name='Фото счётчика'),
        ),
    ]
