# Generated by Django 5.2.17 on 2026-09-21 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0015_alter_controllerreadingsubmission_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controllerreadingsubmission',
            name='reading',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='controller_submissions', to='water.reading', verbose_name='Созданное показание'),
        ),
    ]
