# Generated by Django 5.2.17 on 2026-09-27 20:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0029_security_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalresidentinvite',
            name='basis',
            field=models.CharField(blank=True, max_length=300, verbose_name='Проверенное основание'),
        ),
        migrations.AddField(
            model_name='historicalresidentinvite',
            name='can_represent',
            field=models.BooleanField(default=False, verbose_name='Совершать представительские действия'),
        ),
        migrations.AddField(
            model_name='historicalresidentinvite',
            name='can_submit_water',
            field=models.BooleanField(default=False, verbose_name='Передавать показания воды'),
        ),
        migrations.AddField(
            model_name='historicalresidentinvite',
            name='can_use_appeals',
            field=models.BooleanField(default=False, verbose_name='Создавать и читать свои обращения'),
        ),
        migrations.AddField(
            model_name='historicalresidentinvite',
            name='can_view_account',
            field=models.BooleanField(default=True, verbose_name='Видеть участок и базовые данные'),
        ),
        migrations.AddField(
            model_name='historicalresidentinvite',
            name='can_view_documents',
            field=models.BooleanField(default=False, verbose_name='Видеть документы лицевого счёта'),
        ),
        migrations.AddField(
            model_name='historicalresidentinvite',
            name='can_view_finance',
            field=models.BooleanField(default=False, verbose_name='Видеть начисления и оплаты'),
        ),
        migrations.AddField(
            model_name='historicalresidentinvite',
            name='person',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='water.person', verbose_name='Проверенный человек'),
        ),
        migrations.AddField(
            model_name='historicalresidentinvite',
            name='verified_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кто подтвердил'),
        ),
        migrations.AddField(
            model_name='residentinvite',
            name='basis',
            field=models.CharField(blank=True, max_length=300, verbose_name='Проверенное основание'),
        ),
        migrations.AddField(
            model_name='residentinvite',
            name='can_represent',
            field=models.BooleanField(default=False, verbose_name='Совершать представительские действия'),
        ),
        migrations.AddField(
            model_name='residentinvite',
            name='can_submit_water',
            field=models.BooleanField(default=False, verbose_name='Передавать показания воды'),
        ),
        migrations.AddField(
            model_name='residentinvite',
            name='can_use_appeals',
            field=models.BooleanField(default=False, verbose_name='Создавать и читать свои обращения'),
        ),
        migrations.AddField(
            model_name='residentinvite',
            name='can_view_account',
            field=models.BooleanField(default=True, verbose_name='Видеть участок и базовые данные'),
        ),
        migrations.AddField(
            model_name='residentinvite',
            name='can_view_documents',
            field=models.BooleanField(default=False, verbose_name='Видеть документы лицевого счёта'),
        ),
        migrations.AddField(
            model_name='residentinvite',
            name='can_view_finance',
            field=models.BooleanField(default=False, verbose_name='Видеть начисления и оплаты'),
        ),
        migrations.AddField(
            model_name='residentinvite',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resident_invites', to='water.person', verbose_name='Проверенный человек'),
        ),
        migrations.AddField(
            model_name='residentinvite',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verified_resident_invites', to=settings.AUTH_USER_MODEL, verbose_name='Кто подтвердил'),
        ),
        migrations.AlterField(
            model_name='historicalresidentinvite',
            name='role',
            field=models.CharField(blank=True, choices=[('owner', 'Собственник'), ('representative', 'Представитель'), ('payer', 'Плательщик')], max_length=20, verbose_name='Основание доступа'),
        ),
        migrations.AlterField(
            model_name='residentinvite',
            name='role',
            field=models.CharField(blank=True, choices=[('owner', 'Собственник'), ('representative', 'Представитель'), ('payer', 'Плательщик')], max_length=20, verbose_name='Основание доступа'),
        ),
    ]
