# Generated by Django 5.2.17 on 2026-09-28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0029_security_alert'),
        ('water', '0030_granular_resident_invite'),
    ]

    operations = []
