# Generated by Django 5.2.17 on 2026-09-28 09:46

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0031_merge_0029_security_alert_0030_granular_resident_invite'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardmembership',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='board_memberships', to='water.person', verbose_name='Человек'),
        ),
        migrations.AddField(
            model_name='historicalresidentidentity',
            name='v2_staff_gateway_managed',
            field=models.BooleanField(default=False, editable=False, verbose_name='Служебный вход управляется Access V2'),
        ),
        migrations.AddField(
            model_name='residentidentity',
            name='v2_staff_gateway_managed',
            field=models.BooleanField(default=False, editable=False, verbose_name='Служебный вход управляется Access V2'),
        ),
        migrations.CreateModel(
            name='HistoricalAccessAssignment',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=0)),
                ('role_code', models.CharField(max_length=80, verbose_name='Шаблон роли')),
                ('role_version', models.PositiveIntegerField(default=1, verbose_name='Версия шаблона')),
                ('role_label', models.CharField(max_length=160, verbose_name='Название роли при выдаче')),
                ('allowed_capabilities', models.JSONField(default=list, verbose_name='Максимальный набор прав при выдаче')),
                ('capabilities', models.JSONField(default=list, verbose_name='Активный набор прав')),
                ('scope_type', models.CharField(choices=[('self', 'self'), ('account', 'account'), ('land_plot', 'land_plot'), ('water_group', 'water_group'), ('supply_node', 'supply_node'), ('person', 'person'), ('all', 'all')], max_length=24, verbose_name='Область')),
                ('scope_object_id', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='ID объекта области')),
                ('starts', models.DateField(default=django.utils.timezone.localdate, verbose_name='Полномочие с')),
                ('ends', models.DateField(blank=True, null=True, verbose_name='Полномочие до (не включая)')),
                ('basis', models.CharField(max_length=300, verbose_name='Основание')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='Отозвано')),
                ('revocation_reason', models.CharField(blank=True, max_length=300, verbose_name='Причина отзыва')),
                ('notes', models.TextField(blank=True, verbose_name='Примечание')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('granted_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кто выдал')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='water.person', verbose_name='Человек')),
                ('revoked_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кто отозвал')),
            ],
            options={
                'verbose_name': 'historical Назначение полномочий V2',
                'verbose_name_plural': 'historical Назначения полномочий V2',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalAccessDelegation',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=0)),
                ('capabilities', models.JSONField(default=list, verbose_name='Переданные права')),
                ('scope_type', models.CharField(choices=[('self', 'self'), ('account', 'account'), ('land_plot', 'land_plot'), ('water_group', 'water_group'), ('supply_node', 'supply_node'), ('person', 'person'), ('all', 'all')], default='account', max_length=24, verbose_name='Область')),
                ('scope_object_id', models.PositiveBigIntegerField(verbose_name='ID объекта области')),
                ('starts', models.DateField(default=django.utils.timezone.localdate, verbose_name='Действует с')),
                ('ends', models.DateField(blank=True, null=True, verbose_name='Действует до (не включая)')),
                ('basis', models.CharField(max_length=300, verbose_name='Основание передачи')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='Отозвано')),
                ('revocation_reason', models.CharField(blank=True, max_length=300, verbose_name='Причина отзыва')),
                ('notes', models.TextField(blank=True, verbose_name='Примечание')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('delegate', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='water.person', verbose_name='Кому передаёт')),
                ('delegator', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='water.person', verbose_name='Кто передаёт')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('revoked_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кто отозвал')),
                ('verified_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кто подтвердил')),
            ],
            options={
                'verbose_name': 'historical Делегирование полномочий V2',
                'verbose_name_plural': 'historical Делегирования полномочий V2',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='AccessAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=0)),
                ('role_code', models.CharField(max_length=80, verbose_name='Шаблон роли')),
                ('role_version', models.PositiveIntegerField(default=1, verbose_name='Версия шаблона')),
                ('role_label', models.CharField(max_length=160, verbose_name='Название роли при выдаче')),
                ('allowed_capabilities', models.JSONField(default=list, verbose_name='Максимальный набор прав при выдаче')),
                ('capabilities', models.JSONField(default=list, verbose_name='Активный набор прав')),
                ('scope_type', models.CharField(choices=[('self', 'self'), ('account', 'account'), ('land_plot', 'land_plot'), ('water_group', 'water_group'), ('supply_node', 'supply_node'), ('person', 'person'), ('all', 'all')], max_length=24, verbose_name='Область')),
                ('scope_object_id', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='ID объекта области')),
                ('starts', models.DateField(default=django.utils.timezone.localdate, verbose_name='Полномочие с')),
                ('ends', models.DateField(blank=True, null=True, verbose_name='Полномочие до (не включая)')),
                ('basis', models.CharField(max_length=300, verbose_name='Основание')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='Отозвано')),
                ('revocation_reason', models.CharField(blank=True, max_length=300, verbose_name='Причина отзыва')),
                ('notes', models.TextField(blank=True, verbose_name='Примечание')),
                ('granted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_access_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Кто выдал')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_assignments', to='water.person', verbose_name='Человек')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revoked_access_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Кто отозвал')),
            ],
            options={
                'verbose_name': 'Назначение полномочий V2',
                'verbose_name_plural': 'Назначения полномочий V2',
                'ordering': ['person', 'role_code', '-starts', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('ends__isnull', True), ('ends__gt', models.F('starts')), _connector='OR'), name='access_assignment_dates')],
            },
        ),
        migrations.CreateModel(
            name='AccessDelegation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=0)),
                ('capabilities', models.JSONField(default=list, verbose_name='Переданные права')),
                ('scope_type', models.CharField(choices=[('self', 'self'), ('account', 'account'), ('land_plot', 'land_plot'), ('water_group', 'water_group'), ('supply_node', 'supply_node'), ('person', 'person'), ('all', 'all')], default='account', max_length=24, verbose_name='Область')),
                ('scope_object_id', models.PositiveBigIntegerField(verbose_name='ID объекта области')),
                ('starts', models.DateField(default=django.utils.timezone.localdate, verbose_name='Действует с')),
                ('ends', models.DateField(blank=True, null=True, verbose_name='Действует до (не включая)')),
                ('basis', models.CharField(max_length=300, verbose_name='Основание передачи')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='Отозвано')),
                ('revocation_reason', models.CharField(blank=True, max_length=300, verbose_name='Причина отзыва')),
                ('notes', models.TextField(blank=True, verbose_name='Примечание')),
                ('delegate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_access_delegations', to='water.person', verbose_name='Кому передаёт')),
                ('delegator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_access_delegations', to='water.person', verbose_name='Кто передаёт')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revoked_access_delegations', to=settings.AUTH_USER_MODEL, verbose_name='Кто отозвал')),
                ('verified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verified_access_delegations', to=settings.AUTH_USER_MODEL, verbose_name='Кто подтвердил')),
            ],
            options={
                'verbose_name': 'Делегирование полномочий V2',
                'verbose_name_plural': 'Делегирования полномочий V2',
                'ordering': ['delegator', 'delegate', '-starts', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('ends__isnull', True), ('ends__gt', models.F('starts')), _connector='OR'), name='access_delegation_dates'), models.CheckConstraint(condition=models.Q(('delegator', models.F('delegate')), _negated=True), name='access_delegation_different_people')],
            },
        ),
    ]
